name: CI
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with: { php-version: '8.2' }
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - name: Composer install
        working-directory: app
        run: composer install --no-interaction --prefer-dist
      - name: NPM install & build Tailwind
        working-directory: app
        run: |
          npm ci
          npx tailwindcss -i web/css/input.css -o web/css/tailwind.css --minify
      - name: Prepare SQLite DB & migrate
        working-directory: app
        run: |
          mkdir -p runtime/db && touch runtime/db/test.sqlite
          php yii migrate --interactive=0 || true
      - name: Basic smoke test
        run: php -v && node -v
